import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner"
import TanstackQueryProvide from "@/services/helper/provider/TanstackQuery";
import { Suspense } from "react";
import LoadingDrop from "@/components/LoadingDrop";



export const metadata: Metadata = {
  title: "BloodNeed",
  description: "Generated by Rajat",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<LoadingDrop />}>
          <Toaster position="top-center" richColors />
          <TanstackQueryProvide>
            {children}
          </TanstackQueryProvide>
        </Suspense>
      </body>
    </html>
  );
}
