import Navbar from "@/layout/adminPannel/Navbar";
import Sidebar from "@/layout/adminPannel/Sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Admin Pannel",
    description: "Generated by Admin",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className="flex flex-col">
                <Navbar />
                <div className="flex flex-row">
                    <Sidebar />
                    <div>
                        {children}
                    </div>
                </div>
            </div>

        </>
    );
}
