import Navbar from "@/layout/adminPannel/Navbar";
import Sidebar from "@/layout/adminPannel/Sidebar";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Admin Panel",
    description: "Generated by Admin",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col min-h-screen bg-gray-50/50">
            <Navbar />
            <div className="flex flex-row flex-1 relative">
                <Sidebar />
                <main className="flex-1 w-full overflow-x-hidden">
                    {children}
                </main>
            </div>
        </div>
    );
}
