import Footer from "@/layout/userPannel/Footer";
import Header from "@/layout/userPannel/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "BloodSathi",
    description: "Generated by Rajat user pannel",
};

export default function UserLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            <main className="pt-20">
                {children}
            </main>
            <Footer />
        </>
    );
}
